export const ERROR_CODE = {
  AUTH: {
    UNAUTHORIZED: "UNAUTHORIZED",
    INVALID_USER: "INVALID_USER",
    INVALID_ROLE: "INVALID_ROLE",
    INVALID_USERNAME_OR_PASSWORD: "INVALID_USERNAME_OR_PASSWORD",
    REGISTER_FAILED: "REGISTER_FAILED",
    INVALID_OTP: "INVALID_OTP",
    OTP_EXPIRED: "OTP_EXPIRED",
  },
};
